### ISSUE TITLE
Working AirDrop with AirPortitlwm

### ISSUE THREAD

**Issue by mehmetyukcell** [mavethee/Hackintosh-OpenCore-HP-ProBook-470-G1#1]
Airdrop works in the your system with airportitlwm?

**Comment by mavethee** [comment]
Hi!
Unable to test it because don't have any IPhone around or other device, but in terms of working yeah, it's detected by macOS. Try it out and report how well it works :D 
In a need of testers currently.
![Zrzut ekranu 2020-12-21 o 11 34 35](https://user-images.githubusercontent.com/47083527/102767862-83bcde80-4380-11eb-861c-0de034cb753a.png)
